// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/starlight/ocelot/pkg/core"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Module",
			pos:  position{line: 7, col: 1, offset: 81},
			expr: &actionExpr{
				pos: position{line: 7, col: 11, offset: 93},
				run: (*parser).callonModule1,
				expr: &seqExpr{
					pos: position{line: 7, col: 11, offset: 93},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 7, col: 11, offset: 93},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 7, col: 16, offset: 98},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 7, col: 21, offset: 103},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 11, col: 1, offset: 193},
			expr: &actionExpr{
				pos: position{line: 11, col: 9, offset: 203},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 11, col: 9, offset: 203},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 11, col: 9, offset: 203},
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 9, offset: 203},
								name: "_",
							},
						},
						&labeledExpr{
							pos:   position{line: 11, col: 12, offset: 206},
							label: "first",
							expr: &zeroOrOneExpr{
								pos: position{line: 11, col: 18, offset: 212},
								expr: &ruleRefExpr{
									pos:  position{line: 11, col: 18, offset: 212},
									name: "Any",
								},
							},
						},
						&labeledExpr{
							pos:   position{line: 11, col: 23, offset: 217},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 11, col: 28, offset: 222},
								expr: &seqExpr{
									pos: position{line: 11, col: 29, offset: 223},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 11, col: 29, offset: 223},
											expr: &ruleRefExpr{
												pos:  position{line: 11, col: 29, offset: 223},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 11, col: 32, offset: 226},
											name: "Any",
										},
									},
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 11, col: 38, offset: 232},
							expr: &ruleRefExpr{
								pos:  position{line: 11, col: 38, offset: 232},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "Any",
			pos:  position{line: 15, col: 1, offset: 295},
			expr: &choiceExpr{
				pos: position{line: 15, col: 8, offset: 304},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 15, col: 8, offset: 304},
						name: "List",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 15, offset: 311},
						name: "Vector",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 24, offset: 320},
						name: "Map",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 30, offset: 326},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 39, offset: 335},
						name: "Nil",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 45, offset: 341},
						name: "Bool",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 52, offset: 348},
						name: "Symbol",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 61, offset: 357},
						name: "Key",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 67, offset: 363},
						name: "Number",
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 17, col: 1, offset: 389},
			expr: &choiceExpr{
				pos: position{line: 17, col: 9, offset: 399},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 17, col: 9, offset: 399},
						run: (*parser).callonList2,
						expr: &seqExpr{
							pos: position{line: 17, col: 9, offset: 399},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 17, col: 9, offset: 399},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 17, col: 13, offset: 403},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 17, col: 18, offset: 408},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 17, col: 23, offset: 413},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 19, col: 5, offset: 466},
						run: (*parser).callonList8,
						expr: &seqExpr{
							pos: position{line: 19, col: 5, offset: 466},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 19, col: 5, offset: 466},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&ruleRefExpr{
									pos:  position{line: 19, col: 9, offset: 470},
									name: "Expr",
								},
								&notExpr{
									pos: position{line: 19, col: 14, offset: 475},
									expr: &litMatcher{
										pos:        position{line: 19, col: 15, offset: 476},
										val:        ")",
										ignoreCase: false,
										want:       "\")\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Vector",
			pos:  position{line: 23, col: 1, offset: 544},
			expr: &choiceExpr{
				pos: position{line: 23, col: 11, offset: 556},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 23, col: 11, offset: 556},
						run: (*parser).callonVector2,
						expr: &seqExpr{
							pos: position{line: 23, col: 11, offset: 556},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 23, col: 11, offset: 556},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&labeledExpr{
									pos:   position{line: 23, col: 15, offset: 560},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 23, col: 20, offset: 565},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 23, col: 25, offset: 570},
									val:        "]",
									ignoreCase: false,
									want:       "\"]\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 25, col: 5, offset: 625},
						run: (*parser).callonVector8,
						expr: &seqExpr{
							pos: position{line: 25, col: 5, offset: 625},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 25, col: 5, offset: 625},
									val:        "[",
									ignoreCase: false,
									want:       "\"[\"",
								},
								&ruleRefExpr{
									pos:  position{line: 25, col: 9, offset: 629},
									name: "Expr",
								},
								&notExpr{
									pos: position{line: 25, col: 14, offset: 634},
									expr: &litMatcher{
										pos:        position{line: 25, col: 15, offset: 635},
										val:        "]",
										ignoreCase: false,
										want:       "\"]\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Map",
			pos:  position{line: 29, col: 1, offset: 700},
			expr: &choiceExpr{
				pos: position{line: 29, col: 8, offset: 709},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 29, col: 8, offset: 709},
						run: (*parser).callonMap2,
						expr: &seqExpr{
							pos: position{line: 29, col: 8, offset: 709},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 29, col: 8, offset: 709},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 29, col: 12, offset: 713},
									expr: &ruleRefExpr{
										pos:  position{line: 29, col: 12, offset: 713},
										name: "_",
									},
								},
								&labeledExpr{
									pos:   position{line: 29, col: 15, offset: 716},
									label: "first",
									expr: &zeroOrOneExpr{
										pos: position{line: 29, col: 21, offset: 722},
										expr: &seqExpr{
											pos: position{line: 29, col: 22, offset: 723},
											exprs: []interface{}{
												&ruleRefExpr{
													pos:  position{line: 29, col: 22, offset: 723},
													name: "Key",
												},
												&oneOrMoreExpr{
													pos: position{line: 29, col: 26, offset: 727},
													expr: &ruleRefExpr{
														pos:  position{line: 29, col: 26, offset: 727},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 29, col: 29, offset: 730},
													name: "Any",
												},
											},
										},
									},
								},
								&labeledExpr{
									pos:   position{line: 29, col: 35, offset: 736},
									label: "rest",
									expr: &zeroOrMoreExpr{
										pos: position{line: 29, col: 40, offset: 741},
										expr: &seqExpr{
											pos: position{line: 29, col: 41, offset: 742},
											exprs: []interface{}{
												&oneOrMoreExpr{
													pos: position{line: 29, col: 41, offset: 742},
													expr: &ruleRefExpr{
														pos:  position{line: 29, col: 41, offset: 742},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 29, col: 44, offset: 745},
													name: "Key",
												},
												&oneOrMoreExpr{
													pos: position{line: 29, col: 48, offset: 749},
													expr: &ruleRefExpr{
														pos:  position{line: 29, col: 48, offset: 749},
														name: "_",
													},
												},
												&ruleRefExpr{
													pos:  position{line: 29, col: 51, offset: 752},
													name: "Any",
												},
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 29, col: 57, offset: 758},
									expr: &ruleRefExpr{
										pos:  position{line: 29, col: 57, offset: 758},
										name: "_",
									},
								},
								&litMatcher{
									pos:        position{line: 29, col: 60, offset: 761},
									val:        "}",
									ignoreCase: false,
									want:       "\"}\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 31, col: 5, offset: 820},
						run: (*parser).callonMap26,
						expr: &seqExpr{
							pos: position{line: 31, col: 5, offset: 820},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 31, col: 5, offset: 820},
									val:        "{",
									ignoreCase: false,
									want:       "\"{\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 31, col: 9, offset: 824},
									expr: &ruleRefExpr{
										pos:  position{line: 31, col: 9, offset: 824},
										name: "_",
									},
								},
								&seqExpr{
									pos: position{line: 31, col: 13, offset: 828},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 31, col: 13, offset: 828},
											name: "Key",
										},
										&oneOrMoreExpr{
											pos: position{line: 31, col: 17, offset: 832},
											expr: &ruleRefExpr{
												pos:  position{line: 31, col: 17, offset: 832},
												name: "_",
											},
										},
										&ruleRefExpr{
											pos:  position{line: 31, col: 20, offset: 835},
											name: "Any",
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 31, col: 25, offset: 840},
									expr: &seqExpr{
										pos: position{line: 31, col: 26, offset: 841},
										exprs: []interface{}{
											&oneOrMoreExpr{
												pos: position{line: 31, col: 26, offset: 841},
												expr: &ruleRefExpr{
													pos:  position{line: 31, col: 26, offset: 841},
													name: "_",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 31, col: 29, offset: 844},
												name: "Key",
											},
											&oneOrMoreExpr{
												pos: position{line: 31, col: 33, offset: 848},
												expr: &ruleRefExpr{
													pos:  position{line: 31, col: 33, offset: 848},
													name: "_",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 31, col: 36, offset: 851},
												name: "Any",
											},
										},
									},
								},
								&zeroOrMoreExpr{
									pos: position{line: 31, col: 42, offset: 857},
									expr: &ruleRefExpr{
										pos:  position{line: 31, col: 42, offset: 857},
										name: "_",
									},
								},
								&notExpr{
									pos: position{line: 31, col: 45, offset: 860},
									expr: &litMatcher{
										pos:        position{line: 31, col: 46, offset: 861},
										val:        "}",
										ignoreCase: false,
										want:       "\"}\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Key",
			pos:  position{line: 34, col: 1, offset: 919},
			expr: &actionExpr{
				pos: position{line: 34, col: 8, offset: 928},
				run: (*parser).callonKey1,
				expr: &seqExpr{
					pos: position{line: 34, col: 8, offset: 928},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 34, col: 8, offset: 928},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&ruleRefExpr{
							pos:  position{line: 34, col: 12, offset: 932},
							name: "word",
						},
					},
				},
			},
		},
		{
			name: "Nil",
			pos:  position{line: 38, col: 1, offset: 987},
			expr: &actionExpr{
				pos: position{line: 38, col: 8, offset: 996},
				run: (*parser).callonNil1,
				expr: &litMatcher{
					pos:        position{line: 38, col: 8, offset: 996},
					val:        "nil",
					ignoreCase: false,
					want:       "\"nil\"",
				},
			},
		},
		{
			name: "Bool",
			pos:  position{line: 42, col: 1, offset: 1039},
			expr: &choiceExpr{
				pos: position{line: 42, col: 9, offset: 1049},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 42, col: 9, offset: 1049},
						run: (*parser).callonBool2,
						expr: &litMatcher{
							pos:        position{line: 42, col: 9, offset: 1049},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
					},
					&actionExpr{
						pos: position{line: 44, col: 5, offset: 1092},
						run: (*parser).callonBool4,
						expr: &litMatcher{
							pos:        position{line: 44, col: 5, offset: 1092},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 48, col: 1, offset: 1153},
			expr: &choiceExpr{
				pos: position{line: 48, col: 11, offset: 1165},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 48, col: 11, offset: 1165},
						run: (*parser).callonString2,
						expr: &seqExpr{
							pos: position{line: 48, col: 11, offset: 1165},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 48, col: 11, offset: 1165},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 48, col: 15, offset: 1169},
									expr: &ruleRefExpr{
										pos:  position{line: 48, col: 15, offset: 1169},
										name: "runeChr",
									},
								},
								&litMatcher{
									pos:        position{line: 48, col: 24, offset: 1178},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 50, col: 5, offset: 1240},
						run: (*parser).callonString8,
						expr: &seqExpr{
							pos: position{line: 50, col: 5, offset: 1240},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 50, col: 5, offset: 1240},
									val:        "\"",
									ignoreCase: false,
									want:       "\"\\\"\"",
								},
								&zeroOrMoreExpr{
									pos: position{line: 50, col: 9, offset: 1244},
									expr: &ruleRefExpr{
										pos:  position{line: 50, col: 9, offset: 1244},
										name: "runeChr",
									},
								},
								&notExpr{
									pos: position{line: 50, col: 18, offset: 1253},
									expr: &litMatcher{
										pos:        position{line: 50, col: 19, offset: 1254},
										val:        "\"",
										ignoreCase: false,
										want:       "\"\\\"\"",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "runeChr",
			pos:  position{line: 54, col: 1, offset: 1398},
			expr: &choiceExpr{
				pos: position{line: 54, col: 12, offset: 1411},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 54, col: 12, offset: 1411},
						val:        "[^\"\\\\]",
						chars:      []rune{'"', '\\'},
						ignoreCase: false,
						inverted:   true,
					},
					&ruleRefExpr{
						pos:  position{line: 54, col: 21, offset: 1420},
						name: "runeEsc",
					},
				},
			},
		},
		{
			name: "runeEsc",
			pos:  position{line: 55, col: 1, offset: 1428},
			expr: &seqExpr{
				pos: position{line: 55, col: 12, offset: 1441},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 55, col: 12, offset: 1441},
						val:        "\\",
						ignoreCase: false,
						want:       "\"\\\\\"",
					},
					&choiceExpr{
						pos: position{line: 55, col: 17, offset: 1446},
						alternatives: []interface{}{
							&charClassMatcher{
								pos:        position{line: 55, col: 17, offset: 1446},
								val:        "[abfnrtv\"\\\\]",
								chars:      []rune{'a', 'b', 'f', 'n', 'r', 't', 'v', '"', '\\'},
								ignoreCase: false,
								inverted:   false,
							},
							&seqExpr{
								pos: position{line: 56, col: 13, offset: 1473},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 56, col: 13, offset: 1473},
										val:        "x",
										ignoreCase: false,
										want:       "\"x\"",
									},
									&ruleRefExpr{
										pos:  position{line: 56, col: 17, offset: 1477},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 56, col: 26, offset: 1486},
										name: "hexDigit",
									},
								},
							},
							&seqExpr{
								pos: position{line: 57, col: 13, offset: 1510},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 57, col: 13, offset: 1510},
										val:        "u",
										ignoreCase: false,
										want:       "\"u\"",
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 17, offset: 1514},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 26, offset: 1523},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 35, offset: 1532},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 57, col: 44, offset: 1541},
										name: "hexDigit",
									},
								},
							},
							&seqExpr{
								pos: position{line: 58, col: 13, offset: 1565},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 58, col: 13, offset: 1565},
										val:        "U",
										ignoreCase: false,
										want:       "\"U\"",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 17, offset: 1569},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 26, offset: 1578},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 35, offset: 1587},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 44, offset: 1596},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 53, offset: 1605},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 62, offset: 1614},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 71, offset: 1623},
										name: "hexDigit",
									},
									&ruleRefExpr{
										pos:  position{line: 58, col: 80, offset: 1632},
										name: "hexDigit",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "hexDigit",
			pos:  position{line: 59, col: 1, offset: 1643},
			expr: &charClassMatcher{
				pos:        position{line: 59, col: 12, offset: 1656},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Number",
			pos:  position{line: 61, col: 1, offset: 1708},
			expr: &actionExpr{
				pos: position{line: 61, col: 11, offset: 1720},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 61, col: 11, offset: 1720},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 61, col: 11, offset: 1720},
							expr: &litMatcher{
								pos:        position{line: 61, col: 11, offset: 1720},
								val:        "-",
								ignoreCase: false,
								want:       "\"-\"",
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 61, col: 16, offset: 1725},
							expr: &ruleRefExpr{
								pos:  position{line: 61, col: 16, offset: 1725},
								name: "digit",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 61, col: 23, offset: 1732},
							expr: &seqExpr{
								pos: position{line: 61, col: 24, offset: 1733},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 61, col: 24, offset: 1733},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 61, col: 28, offset: 1737},
										expr: &ruleRefExpr{
											pos:  position{line: 61, col: 28, offset: 1737},
											name: "digit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 61, col: 37, offset: 1746},
							expr: &seqExpr{
								pos: position{line: 61, col: 38, offset: 1747},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 61, col: 38, offset: 1747},
										val:        "e",
										ignoreCase: true,
										want:       "\"e\"i",
									},
									&zeroOrOneExpr{
										pos: position{line: 61, col: 43, offset: 1752},
										expr: &litMatcher{
											pos:        position{line: 61, col: 43, offset: 1752},
											val:        "-",
											ignoreCase: false,
											want:       "\"-\"",
										},
									},
									&oneOrMoreExpr{
										pos: position{line: 61, col: 48, offset: 1757},
										expr: &ruleRefExpr{
											pos:  position{line: 61, col: 48, offset: 1757},
											name: "digit",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 65, col: 1, offset: 1849},
			expr: &actionExpr{
				pos: position{line: 65, col: 11, offset: 1861},
				run: (*parser).callonSymbol1,
				expr: &seqExpr{
					pos: position{line: 65, col: 11, offset: 1861},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 65, col: 11, offset: 1861},
							name: "word",
						},
						&zeroOrOneExpr{
							pos: position{line: 65, col: 16, offset: 1866},
							expr: &ruleRefExpr{
								pos:  position{line: 65, col: 16, offset: 1866},
								name: "suffix",
							},
						},
					},
				},
			},
		},
		{
			name: "word",
			pos:  position{line: 68, col: 1, offset: 1942},
			expr: &seqExpr{
				pos: position{line: 68, col: 9, offset: 1952},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 68, col: 9, offset: 1952},
						name: "letter",
					},
					&zeroOrMoreExpr{
						pos: position{line: 68, col: 16, offset: 1959},
						expr: &choiceExpr{
							pos: position{line: 68, col: 17, offset: 1960},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 68, col: 17, offset: 1960},
									name: "letter",
								},
								&ruleRefExpr{
									pos:  position{line: 68, col: 26, offset: 1969},
									name: "digit",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "suffix",
			pos:  position{line: 70, col: 1, offset: 1987},
			expr: &charClassMatcher{
				pos:        position{line: 70, col: 11, offset: 1999},
				val:        "[!?*]",
				chars:      []rune{'!', '?', '*'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "digit",
			pos:  position{line: 72, col: 1, offset: 2031},
			expr: &charClassMatcher{
				pos:        position{line: 72, col: 10, offset: 2042},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "letter",
			pos:  position{line: 74, col: 1, offset: 2100},
			expr: &choiceExpr{
				pos: position{line: 74, col: 11, offset: 2112},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 74, col: 11, offset: 2112},
						val:        "[\\p{L}]",
						classes:    []*unicode.RangeTable{rangeTable("L")},
						ignoreCase: false,
						inverted:   false,
					},
					&litMatcher{
						pos:        position{line: 74, col: 21, offset: 2122},
						val:        "_",
						ignoreCase: false,
						want:       "\"_\"",
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 76, col: 1, offset: 2178},
			expr: &choiceExpr{
				pos: position{line: 76, col: 19, offset: 2198},
				alternatives: []interface{}{
					&charClassMatcher{
						pos:        position{line: 76, col: 19, offset: 2198},
						val:        "[\\p{Z}]",
						classes:    []*unicode.RangeTable{rangeTable("Z")},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 76, col: 29, offset: 2208},
						val:        "[\\p{C}]",
						classes:    []*unicode.RangeTable{rangeTable("C")},
						ignoreCase: false,
						inverted:   false,
					},
					&ruleRefExpr{
						pos:  position{line: 76, col: 39, offset: 2218},
						name: "Comment",
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 78, col: 1, offset: 2238},
			expr: &choiceExpr{
				pos: position{line: 78, col: 12, offset: 2251},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 78, col: 12, offset: 2251},
						name: "SingleLineComment",
					},
					&ruleRefExpr{
						pos:  position{line: 78, col: 32, offset: 2271},
						name: "MultiLineComment",
					},
				},
			},
		},
		{
			name: "SingleLineComment",
			pos:  position{line: 79, col: 1, offset: 2288},
			expr: &seqExpr{
				pos: position{line: 79, col: 21, offset: 2310},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 79, col: 21, offset: 2310},
						val:        "//",
						ignoreCase: false,
						want:       "\"//\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 79, col: 26, offset: 2315},
						expr: &seqExpr{
							pos: position{line: 79, col: 27, offset: 2316},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 79, col: 27, offset: 2316},
									expr: &ruleRefExpr{
										pos:  position{line: 79, col: 28, offset: 2317},
										name: "EOL",
									},
								},
								&anyMatcher{
									line: 79, col: 32, offset: 2321,
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 79, col: 36, offset: 2325},
						name: "EOL",
					},
				},
			},
		},
		{
			name: "MultiLineComment",
			pos:  position{line: 80, col: 1, offset: 2329},
			expr: &seqExpr{
				pos: position{line: 80, col: 21, offset: 2351},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 80, col: 21, offset: 2351},
						val:        "/*",
						ignoreCase: false,
						want:       "\"/*\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 80, col: 26, offset: 2356},
						expr: &seqExpr{
							pos: position{line: 80, col: 27, offset: 2357},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 80, col: 27, offset: 2357},
									expr: &litMatcher{
										pos:        position{line: 80, col: 28, offset: 2358},
										val:        "*/",
										ignoreCase: false,
										want:       "\"*/\"",
									},
								},
								&anyMatcher{
									line: 80, col: 33, offset: 2363,
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 80, col: 37, offset: 2367},
						val:        "*/",
						ignoreCase: false,
						want:       "\"*/\"",
					},
				},
			},
		},
		{
			name: "EOL",
			pos:  position{line: 82, col: 1, offset: 2387},
			expr: &choiceExpr{
				pos: position{line: 82, col: 8, offset: 2396},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 82, col: 8, offset: 2396},
						val:        "\n",
						ignoreCase: false,
						want:       "\"\\n\"",
					},
					&ruleRefExpr{
						pos:  position{line: 82, col: 15, offset: 2403},
						name: "EOF",
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 84, col: 1, offset: 2422},
			expr: &notExpr{
				pos: position{line: 84, col: 8, offset: 2431},
				expr: &anyMatcher{
					line: 84, col: 9, offset: 2432,
				},
			},
		},
	},
}

func (c *current) onModule1(expr interface{}) (interface{}, error) {
	return core.List(expr.([]core.Any)), nil
}

func (p *parser) callonModule1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onModule1(stack["expr"])
}

func (c *current) onExpr1(first, rest interface{}) (interface{}, error) {
	return join(first, rest, 1), nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["first"], stack["rest"])
}

func (c *current) onList2(expr interface{}) (interface{}, error) {
	return core.List(expr.([]core.Any)), nil
}

func (p *parser) callonList2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList2(stack["expr"])
}

func (c *current) onList8() (interface{}, error) {
	return core.Nil{}, errors.New("not terminated")
}

func (p *parser) callonList8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList8()
}

func (c *current) onVector2(expr interface{}) (interface{}, error) {
	return core.Vector(expr.([]core.Any)), nil
}

func (p *parser) callonVector2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVector2(stack["expr"])
}

func (c *current) onVector8() (interface{}, error) {
	return core.Nil{}, errors.New("not terminated")
}

func (p *parser) callonVector8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVector8()
}

func (c *current) onMap2(first, rest interface{}) (interface{}, error) {
	return core.Map(merge(first, rest, 0, 2)), nil
}

func (p *parser) callonMap2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMap2(stack["first"], stack["rest"])
}

func (c *current) onMap26() (interface{}, error) {
	return core.Nil{}, errors.New("not terminated")
}

func (p *parser) callonMap26() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMap26()
}

func (c *current) onKey1() (interface{}, error) {
	return core.Key(string(c.text)), nil
}

func (p *parser) callonKey1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKey1()
}

func (c *current) onNil1() (interface{}, error) {
	return core.Nil{}, nil
}

func (p *parser) callonNil1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNil1()
}

func (c *current) onBool2() (interface{}, error) {
	return core.Bool(true), nil
}

func (p *parser) callonBool2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool2()
}

func (c *current) onBool4() (interface{}, error) {
	return core.Bool(false), nil
}

func (p *parser) callonBool4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool4()
}

func (c *current) onString2() (interface{}, error) {
	return core.String{Val: string(c.text)}.Unquote()
}

func (p *parser) callonString2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString2()
}

func (c *current) onString8() (interface{}, error) {
	return core.Nil{}, errors.New("not terminated")
}

func (p *parser) callonString8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString8()
}

func (c *current) onNumber1() (interface{}, error) {
	return core.String{Val: string(c.text)}.Number()
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onSymbol1() (interface{}, error) {
	return core.Symbol{Val: string(c.text), Pos: pos(c.pos)}, nil
}

func (p *parser) callonSymbol1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
